AllCops:
  TargetRubyVersion: 2.3
LineLength:
  Enabled: no
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: yes
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
MethodLength:
  Enabled: no
Metrics/AbcSize:
  Enabled: no
Metrics/BlockLength:
  Max: 90
Metrics/ClassLength:
  Enabled: no
Metrics/CyclomaticComplexity:
  Enabled: no
Metrics/LineLength:
  Enabled: no
Metrics/PerceivedComplexity:
  Enabled: no
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
